### ISSUE TITLE
Translation tests!

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-scanner#2]
For tables this size, consistency tests are useful of the generated tables is useful

Most symbols round trip. Those that don't would be noted in a list in the test and all others would be checked for
round-tripping. The number of keys in each table agrees. The set of symbols that maps back to a WL long name is eactly the set of WL symbols.

**Comment by GarkGarcia** [comment]
@rocky I figure we can mostly copy the tests from mathics/Mathics (the ones in `test_nonascii.py`) and adapt them.

**Comment by GarkGarcia** [comment]
This was partially fixed on the commits prior to https://github.com/Mathics3/mathics-scanner/pull/8/commits/754a97ae156908512f08b56043e4776e70c16f33 (see https://github.com/Mathics3/mathics-scanner/pull/8#issuecomment-770434121), but the tests implemented in there only guarantee that the YAML table is self-consistent.

I don't think testing the quality of the translation routines is viable (i.e. testing if the translation is actually good), as this is subjective information we don't have access to. May I close this?

**Comment by rocky** [comment]
There are many things that aren't subjective, like counts and sums. I've mentioned some of these things before, so I don't want to repeat. 

When I get a chance, I'll look over the tests to make sure we catch those kinds of things. Until then let's leave this open.

**Comment by GarkGarcia** [comment]
> There are many things that aren't subjective, like counts and sums. I've mentioned some of these things before, so I don't want to repeat.

The example of something that could be counted is already implemented.

> When I get a chance, I'll look over the tests to make sure we catch those kinds of things. Until then let's leave this open.

Great!

> Some translations needed reported as bugs. While perhaps subjective, they aren't that subjective. What was there when nothing was done was deficient, it was noticed by others, and we've addressed that. We should test that the decision that was made whatever it was (and took a bit of time in deciding) is checked to make sure we don't regress.

Makes sense. We could add checks for the entries that have comments explaining the decisions. Indeed, the table was (and most likely still is) deficient, I just don't see how to test this sort of thing in bulk, but checking for regressions in particular cases is a great idea.

**Comment by GarkGarcia** [comment]
Now that I think about it, the testing of the JSON conversion is somewhat deficient. By far (as of now), the biggest source of bugs have been the YAML table, but we should definitively put some checks in place for script that converts the YAML table to the precompiled JSON tables. @rocky I tried to add checks for anything I could think of, but I'm sure you'll be able to find room for improvement in there.

**Comment by GarkGarcia** [comment]
>  We should test that the decision that was made whatever it was (and took a bit of time in deciding) is checked to make sure we don't regress.

Implemented in https://github.com/Mathics3/mathics-scanner/pull/8/commits/f9b75d85fc03dc25d80be47cd583f9975f1be292.

**Comment by rocky** [comment]
At some point sufficient tests were added.
