### ISSUE TITLE
requirements-extra.txt not included in released source code and missing description

### ISSUE THREAD

**Issue by vicp74** [Mathics3/mathics-scanner#29]
The file [requirements-extra.txt](https://github.com/Mathics3/mathics-scanner/blob/master/requirements-extra.txt) is not included in the [released source code](https://github.com/Mathics3/mathics-scanner/releases/download/1.2.1/Mathics_Scanner-1.2.1.tar.gz), so building directly from that is not possible.

Since I'm packaging this for [AUR](https://aur.archlinux.org/packages/mathics/), I would like to have a brief description of what each extra requirement brings. In this case, what would a user gain by installing ujson? I know it used to say `#Optional Used in mathics_scanner.characters` but that doesn't mean too much in terms of why (not) installing it.

**Comment by TiagoCavalcanteTrindade** [comment]
@vicp74 ujson is faster than the native json library.

About the file, I gonna look at it.

**Comment by rocky** [comment]
First and foremost thanks for the quick and up-to-date packages on AUR. You rock!

Also thanks for bringing up the breakage quickly.  I renamed `requirements-extra.txt` to `requirements-full.txt` with the intention of making this more clear and to match the form of installation via `pip install -e. .[full]` (or change `.` with the name of the package).

I have just released 1.2.2  to address the mistake in packaging. 

As for `ujson`. That isn't so important here but it is more important clients that use the JSON produced, mathics in particular.

It needs to load JSON and ujson is faster than loading via Python's native format "pickle" or any kinds of YAML or Python's builtin JSON. 

And in the future, if you run into problems or questions in packaging please let me know just as you've done here.

**Comment by rocky** [comment]
> @vicp74 ujson is faster than the native json library.

Yes, and not just _faster_ but `_fastest`. However it might not be supported on pyston 2.2 and that in general is 30% faster at running mathics.

> 
> About the file, I gonna look at it.

Hopefully, with release 1.2.2 things are fixed. However, as we see here, I make mistakes. Lots of them. (That's one reason I've written so many debuggers). 

So please double check and fix things if there is still a problem. Thanks!

**Comment by rocky** [comment]
@vicp74 @TiagoCavalcanteTrindade One last thing which is unrelated superficially but really related. There will be a release of Mathics 3.0.0 (and then mathicsscript and then mathics django) I hope within 24 hours. 

See https://github.com/mathics/Mathics/blob/master/CHANGES.rst for what's up here.

**Comment by rocky** [comment]
@vicp74 As mentioned Mathics 3.0.0 and mathicsscript  3.2.0 are out. The thing to be aware of with mathicscript is that it is better to install the "full" dependencies as that gives the ability to show 2D graphs and plots using mathplotlib.

**Comment by vicp74** [comment]
> First and foremost thanks for the quick and up-to-date packages on AUR. You rock!

I enjoy doing it! :smiley: 

>> The file requirements-extra.txt is not included in the released source code
>
> Hopefully, with release 1.2.2 things are fixed.

I may be missing something, but I can't find [requirements-full.txt](https://github.com/Mathics3/mathics-scanner/blob/master/requirements-full.txt) in the released [Mathics_Scanner-1.2.2.tar.gz](https://github.com/Mathics3/mathics-scanner/releases/download/1.2.2/Mathics_Scanner-1.2.2.tar.gz), which is the one I've been calling "source code" until now. 

I see there's a requirements-dev.txt in the one named [Source code (zip or tar.gz)](https://github.com/Mathics3/mathics-scanner/archive/refs/tags/1.2.2.tar.gz), but no requirements-full.txt there either.

> and not just faster but fastest . However it might not be supported on pyston 2.2 and that in general is 30% faster at running mathics.

Thanks for the explanation about ujson.

**Comment by rocky** [comment]
> > First and foremost thanks for the quick and up-to-date packages on AUR. You rock!
> 
> I enjoy doing it! 
> 
> > > The file requirements-extra.txt is not included in the released source code
> > 
> > 
> > Hopefully, with release 1.2.2 things are fixed.
> 
> I may be missing something, but I can't find [requirements-full.txt](https://github.com/Mathics3/mathics-scanner/blob/master/requirements-full.txt) in the released [Mathics_Scanner-1.2.2.tar.gz](https://github.com/Mathics3/mathics-scanner/releases/download/1.2.2/Mathics_Scanner-1.2.2.tar.gz), which is the one I've been calling "source code" until now.
> 

Sorry - I make lots of mistakes. That's one reason I work on [de](https://github.com/rocky/zshdb)[bug](https://github.com/rocky/python3-trepan)[ers](https://github.com/rocky/remake). 

> I see there's a requirements-dev.txt in the one named [Source code (zip or tar.gz)](https://github.com/Mathics3/mathics-scanner/archive/refs/tags/1.2.2.tar.gz), but no requirements-full.txt there either.

The dev file has only what's needed for development, like test frameworks (pytest). Perhaps the next release I'll do for "dev" what was done for "full", so that folks who package or pull this can also run the tests.


> 
> > and not just faster but fastest . However it might not be supported on pyston 2.2 and that in general is 30% faster at running mathics.
> 
> Thanks for the explanation about ujson.

**Comment by vicp74** [comment]
> Sorry - I make lots of mistakes. That's one reason I work on debuggers.

Haha don't worry, it's fixed now. You can close this issue.
