### ISSUE TITLE
named-characters.yml is missing in released tar ball

### ISSUE THREAD

**Issue by susnux** [Mathics3/mathics-scanner#32]
The release [tar ball](https://github.com/Mathics3/mathics-scanner/releases/download/1.2.3/Mathics_Scanner-1.2.3.tar.gz) as well as the pypi release is missing the `mathics_scanner/data/named-characters.yml` file, so running the testsuite will fail

**Comment by rocky** [comment]
Should be fixed now. Please double check though and close after verifying.

**Comment by susnux** [comment]
Works, thank you!
