### ISSUE TITLE
Wrong behaviour in parsing escaped backslash

### ISSUE THREAD

**Issue by mmatera** [Mathics3/mathics-scanner#46]
Consider the input in the 

```
In[1]:= "\\[Integral]" == "\\" <> "[Integral]"
```

In WMA, the result is 
```
Out[1]= True
```
On the other hand, in Mathics the result is 
```Out[1]= False``` 

The reason is mathics-scanner  parses the LHS as `"\u222b"`, which is different to the RHS  `"\[Integral]"`

I found it when I tried to write tests for https://github.com/Mathics3/mathics-core/pull/541

**Comment by rocky** [comment]
@mmatera what does `StringLength["\\[Integral]"]` evaluate to?

**Comment by mmatera** [comment]
In WMA:
```
In[1]:= StringLength["\\[Integral]"]

Out[1]= 11
 ```
On the other hand,
```
In[2]:= StringLength["\[Integral]"]

Out[2]= 1
 ```
